### ISSUE TITLE
Bus place in ecosystem

### ISSUE THREAD

**Issue by raventid** [i-m-v-j/Bus#6]
Hi!
I'm currently looking for a nice and well supported mqtt client library for Elixir. There are few options and the most popular now is https://github.com/suvash/hulaaki. What are your plans for the Bus and why have you created new client from scratch instead of using existing package? I had a few problems with hulaaki and I think it's code a bit bloated, so I'm still looking for alternatives))

**Comment by 00imvj00** [comment]
Hello @raventid thank you for taking interest in Bus.

Like you, i was also using hulaaki, and i had following problems with hulaaki.
1. It is not built using mix/ elixir style, so you need to setup and do all manually.
2. There is no support for automatic reconnect, so u need to manage that also.
3. We need to do process management manually.
4. There is no automatic packet_id support, so when u send publish/ subscribe a packet, you need to give back a send packet id, but i think it should be handled internally, because id should be 16 bit, but end user may or may not know that, so that can create bit of issues and confuse the lib user.

Among other lot of problems. i had talk with creator and couldn't get good support. so thought to create one myself.

i tried contributing hulaaki, but i din't like the overall flow. so i decided to prototype and see i can build better one.

i started using bus and it is right now better than hulaaki, but this is just started. there are lot of improvements i already planned that give end user very best experience using bus just like ecto or other. and i am committed to support bus for very long time.
